### ISSUE TITLE
The Github image link is huge

### ISSUE THREAD

**Issue by jkutner** [buildpacks/registry-api#19]
It should be smaller

![image](https://user-images.githubusercontent.com/1589/107051940-aec58b00-6792-11eb-84c0-c7ef46ef8516.png)

**Comment by elbandito** [comment]
@jkutner I'm wondering if we should consider some more generic than github?  It just occurred to me that the `homepage` can be anything e.g. github, gitlab, some personal website, etc.

**Comment by jkutner** [comment]
Yea, it should probably be like the forking image in the Git logo or similar

**Comment by arnav-t** [comment]
I'll take this up too. I'll open the PR after the current one's merged.
