### ISSUE TITLE
Empty license info should say "Unknown"

### ISSUE THREAD

**Issue by jkutner** [buildpacks/registry-api#20]
When there's no license, the detail page should say "Unknown"

![image](https://user-images.githubusercontent.com/1589/107052054-d157a400-6792-11eb-99ff-b8dd93d5b5db.png)

**Comment by ParseSnip** [comment]
Hi, can I help with this issue?

**Comment by jkutner** [comment]
@ParseSnip absolutely. We'd love to have your help. @elbandito can help coordinate. 

I believe the relavant code is here: 
https://github.com/buildpacks/registry-api/blob/main/app/javascript/components/buildpack/Detail.tsx#L59-L72

**Comment by ParseSnip** [comment]
Ok can you assign it to me ?
Thanks

**Comment by elbandito** [comment]
Let me know if you have any questions. @ParseSnip
