### ISSUE TITLE
Registry landing page could be more helpful

### ISSUE THREAD

**Issue by ImJasonH** [buildpacks/registry-api#43]
Going to https://registry.buildpacks.io leads me to a UI that's not terribly descriptive about what I'm supposed to do now. Why am I here? What's a buildpack even?

<img width="819" alt="Screen Shot 2021-02-25 at 12 20 02 PM" src="https://user-images.githubusercontent.com/210737/109191143-dbead500-7763-11eb-9725-45b49da412cf.png">

-----

Some kind of link to docs on buildpacks.io could go a long way.

**Comment by Brahyt** [comment]
Ill take this one on.

**Comment by jkutner** [comment]
There is a link to the docs at the top of the page, but it sounds like it wasn't obvious. We could add a sentence or two of text below the search bar that says what this page is all about.

**Comment by jkutner** [comment]
Fixed by #46
